### PR TITLE
Add two version badges

### PR DESCRIPTION
**Pull request by janpio**
This adds two version badges that show the latest GitHub and NPM versions.

### CODE REVIEW

**Comment by oliversalzburg** [comment]
I don't think the "GitHub version" works. It should indicate 1.1.7-dev, but shows 1.1.6.

**Comment by janpio** [comment]
That is the "last release version on GitHub" - but I see how this might be confusing in our case. Hmm...

**Comment by oliversalzburg** [comment]
Oh, I see. Would there be any reason why that would be different from the npm version though?

**Comment by janpio** [comment]
Forgotten to publish on npm. Happens. The badge makes sure people will ask about the mismatch.

**Pull request merged**
