### PR TITLE
CB-9071 Update test framework plugin to use Jasmine 2.4.1

### PR DESCRIPTION
**Pull request by marcuspridham**
Updating Jasmine version from 2.2.0 to 2.3.4.

### CODE REVIEW

**Comment by nikhilkh** [comment]
@dblotsky Can you take a look at this change?

**Comment by dblotsky** [comment]
On it.

**Comment by dblotsky** [comment]
I've tested on iOS and it seems to work fine. @marcuspridham, did you make any custom changes, or is it just an update of the files that belong to Jasmine?

**Comment by marcuspridham** [comment]
Just updating the Jasmine files.  No custom changes.

**Comment by dblotsky** [comment]
Ok, LGTM. Merging.

**Comment by dblotsky** [comment]
Due to some bugs with iOS, I'm unable to test this after the rebase on my machine. @marcuspridham have you verified that the code works?

**Comment by nikhilkh** [comment]
Also, Marcus have you filed the Apache iCLA? If not please sign, scan and send one to secretary@apache.org: http://www.apache.org/licenses/icla.txt

**Comment by marcuspridham** [comment]
Code does work.  I have been running my plugin tests with this change.

For the Cordova mobile spec, I don't have an iOS device on me right now.  An iOS 8.3 simulator gives the same result with and without my change (459 spec, 11 failures, 3 pending) this is against Cordova iOS 3.8.0.  Failures seem to be with contacts and location which I don't think work with a simulator.  

I have signed the Apache iCLA and committed changes to Cordova before.

**Pull request closed without merging**
